spring:
  application:
    name: SpaceObj
  datasource:
    url: jdbc:mysql://localhost:3307/school?useSSL=false&serverTimezone=UTC&characterEncoding=utf8  # URL连接
    username: root                                     #账号
    password: root                                     # 密码
    driver-class-name: com.mysql.cj.jdbc.Driver       # 连接引擎
mybatis:
    mapper-locations: classpath:/mappers/*.xml,classpath:/mapper/*.xml   # MyBatis XML 映射文件的位置
    type-aliases-package: com.spaceobj.spaceobj.pojo    # 实体类所在的包路径
    configuration:
      map-underscore-to-camel-case: true            # 支持驼峰命名转换
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
            include: beans

# SpringDoc OpenAPI 3 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.spaceobj.spaceobj.controller

# 日志配置
logging:
  level:
    com.spaceobj.spaceobj: DEBUG
    org.springframework.web.socket: DEBUG